### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by tolgaaaltas** [zerosonesfun/hashtags#1]
This extension does not work correctly with Turkish characters.
![Screenshot_20190804-101727__02](https://user-images.githubusercontent.com/10291048/62420822-76c32080-b6a1-11e9-92e6-1eaf80f0e5e8.jpg)

**Comment by zerosonesfun** [comment]
Closing issue. This is fixed. But, in the future more work is needed to fine tune the regex.
