### ISSUE TITLE
Original purify.min.js code?

### ISSUE THREAD

**Issue by NoahOrtega** [zerosonesfun/hashtags#2]
I'm trying to understand the JavaScript in your extension but as a beginner it's quite confusing without variable names or any comments.  I understand it is minimized for efficiency but is there any way I could see your original code?

Apologies if this is the wrong way to ask this question. Great work on this extension!

**Comment by zerosonesfun** [comment]
Honestly, I don’t recall why I added the purify.min.js. It may not be necessary. I know that it “sanitizes HTML and prevents XSS attacks.” 

One could fork this and remove the purify.js and I bet it’d work just fine.
