### ISSUE TITLE
This extension breaks fof/formatting display

### ISSUE THREAD

**Issue by studosi-flarum** [zerosonesfun/hashtags#3]
Upon turning on this extension, certain autoembedded elements have broken displays:

![image](https://user-images.githubusercontent.com/62252935/77236062-3e823b00-6bbb-11ea-8185-dce13219877d.png)

How it should look like:

![image](https://user-images.githubusercontent.com/62252935/77236073-55289200-6bbb-11ea-8331-6d2cb820834b.png)

It is possible that the hashtags extension is messing with some CSS option, or perhaps getting confused by some hashtagged expression when parsing posts.

Also, the reason I'm sure it's hashtags is because I've found the culprit by elimination. I've only seen this happen with Medium links (and not even all Medium links), others like reddit, youtube, google drive etc. work fine.

This happens on nginx, beta 12 and php 7.4.3.

**Comment by zerosonesfun** [comment]
This extension looks for any text which starts with “#.” I assume certain embeds use the # character for various reasons, hence the conflict. There are no plans at this time to make this compatible with all extensions.
