### ISSUE TITLE
Wrong search parameter

### ISSUE THREAD

**Issue by dyanakiev** [zerosonesfun/hashtags#4]
Currently it uses `https://website.com/all?q=test` but it should be only `https://website.com/?q=test` i use flarum 0.1.0-beta.14 and current url just redirects me to the front page.

**Comment by zerosonesfun** [comment]
I can’t reproduce this with beta 14 on a live site. The reason “all” was added to the search URL has to do with people who set the tags page as their homepage. If you do the URL the way you suggested, and someone sets their homepage to the tags page, it won’t work.
